CREATE TABLE flow1keys (
    id INTEGER PRIMARY KEY,
    FREQ TEXT(1),  
    TIME_PERIOD INTEGER,  
    REF_AREA TEXT(2),  
    INDICATOR TEXT(4),  
    ACTIVITY TEXT,  
    NUMBER_EMPL TEXT,  
    PRODUCT TEXT(2),  
    TURNOVER TEXT(2),  
    CLIENT_RESIDENCE TEXT(2),  
    UNIT_MEASURE TEXT(3),  
    UNIQUE (FREQ, TIME_PERIOD, REF_AREA, INDICATOR, ACTIVITY, NUMBER_EMPL, PRODUCT, TURNOVER, CLIENT_RESIDENCE, UNIT_MEASURE)
);

CREATE TABLE flow1values (
    timestamp INTEGER,
    keyID INTEGER,
    OBS_STATUS TEXT(1),
    OBS_STATUS_1 TEXT(1),
    CONF_STATUS TEXT(1),
    CONF_STATUS_1 TEXT(1),
    OBS_VALUE REAL,
    UNIT_MULT TEXT(1),  
    DECIMALS TEXT(1),
    DOMINANCE TEXT,  
    SHARE_SECOND TEXT,  
    COMMENT_OBS TEXT,
    FOREIGN KEY (keyID) REFERENCES flow1keys(id)
);
